name: Testes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testar-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install pandas openpyxl pytest

      - name: Rodar os testes
        run: python -m pytest tests/ -v
